### ISSUE TITLE
Germany appears to have incorrect death data

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#143] opened 2020-12-16 19:22 UTC
Hi,
The data in Germany's "deaths" field does not appear to be correct. It does not match that published by the ECDPC or the Robert Koch Institute. Importantly, the daily change in deaths calculated by this data on GitHub produces a series showing that deaths have already peaked, and are now declining, despite the continued increase in daily cases and the continued increases in daily death data published by the aforementioned sources as well as Johns Hopkins and Our World in Data.
Any information would be greatly appreciated.
-Hunter

**Comment by eguidotti** [comment] 2020-12-16 20:24
Hi, thanks for your message. 
I'm not able to reproduce the issue. Indeed I can see on the [RKI Dashboard](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_1/) the same data that I get with:
```R
x <- covid19("DEU")
```
In particular, on 2020-12-15 I see on both sources `confirmed = 1379238`, `deaths = 23427`.
After the issues in #130 and #131, the data for Germany in this repo is obtained from https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74

Ragarding the other sources, I guess Our World in Data uses the confirmed and deaths from JHU. I'm not surprised of some differences with JHU or ECDPC. But the data in this repo should definitely match with those published by the Robert Koch Institute.

Can you be a little more specific on the mismatch you found?
Thanks!

**Comment by hlcny** [comment] 2020-12-16 23:19
This is strange. I’ve attached a spreadsheet. This contains case and death data from the ECDC and Koch from the CEIC database (this is a commercial data vendor). Calculations on new cases and new deaths are in columns H and I derived from the Koch. As you can see, they generally match the ECDC data exactly. I also downloaded a csv file directly from the ECDC and confirmed that they match the ECDC from the vendor.

I’ve pasted a screenshot of the data I get from:

covid19(country=”DEU”, level=1, raw=T).

I agree that on 2020-12-15 deaths = 23427, which matches the Koch. However, the increase in deaths on 12/15 that I calculate is 952, which is equal to the number that is shown on  the Koch dashboard at RKI Dashboard <https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4/page/page_1/>  on that day, for which I’ve also pasted a screenshot. 

The increase in deaths from covid19 is only 34 deaths on that day. I’m not an expert on Germany covid death data, but when I presented the chart to several colleagues today, they said it looked wrong…the chart I made with covid19 shows a death curve that has already peaked and is trending down, while the Koch shows it still rising (as do other sources I’ve looked at). of course, it’s possible that they are wrong and that actually the covid19 data is correct…

**Comment by eguidotti** [comment] 2020-12-17 12:47
Hi @hlcny, thanks for the info. Now I see the problem.
As I posted yesterday, on 2020-12-15 the `covid19` was returning confirmed=1379238 and deaths = 23427.
Today, the `covid19` function is returning different data for yesterday 2020-12-15: confirmed=1389285 and deaths=24097.

Unfortunately, this does seem a problem due to the way RKI is updating the data. They are updating the data retroactively. In other words, today they are also updating records of months ago. 

After investigating the issue, I found out that there can be a huge lag between the date the case was confirmed and the date the RKI updates the record in the data file. For instance, today the RKI inserted some new confirmed cases that date back to March! 

If one simply take the difference between the total numbers released today by RKI and those released yesterday, we end up counting cases of several month ago as though they were confirmed today. This is NOT what done by this repo. Each hour this repo downloads the latest version of the RKI dataset and compute the numbers from scratch. In this way, cases of March are assigned to March and cases of today are counted for today. This explains why the numbers you obtained with `covid19` are smaller than those provided by the other sources. 

For deaths, it is slightly different. Indeed, the RKI does not provide the exact date of death but only releases an indicator for deaths that were inserted today. This means that:
- the only record that should match across all sources is the total number of deaths as of today
- there is no way to reconstruct the historical number of deaths unless using the daily archive of RKI files 
- the increase in deaths today can be obtained by using the indicator of new deaths provided by the RKI. However there is no way to know if these "new deaths" are really today's deaths or just new records inserted in the database dating back to months ago (as for the number of cases)
- this repo uses the date of notification of the case as a proxy for the date of death and reconstructs the historical series. However, this approach may not be correct and would be probably better to switch provider for the number of deaths.

Since I believe all the other sources are in some way based on RKI for Germany, I would highly recommend to read the [RKI documentation](https://covid19-de-stats.sourceforge.io/rki-fall-tabelle.html#meldeverzug). The code we use to process the data is very transparent and you can find it [here](https://github.com/covid19datahub/COVID19/blob/master/R/ds_gov_de.R).

Your feedback would be much appreciated. Thanks!

**Comment by eguidotti** [comment] 2020-12-21 16:51
Hi there, I confirm that RKI is updating the data retroactively and their "new cases" actually correspond to the "new records" inserted in the database regardless of the date of the case. The same applies to deaths. Other researchers stumbled over the same contradictions. Here the great reply I received via email that sheds light on this issue.

> The new cases reported on the dashboard are actually old cases (or, at least, some are old). I stumbled over the same contradictions a couple of weeks ago and sent a request to the RKI. I got in touch with a competent employee who made me understand.

> Every day the German local health offices (approx. 420) sent a list of confirmed cases to the RKI (usually Excel files). Each case of the list has a confirmation date and can be one, two, three ..weeks old with most cases from within the current week. This is due to test delays, local reconfirmation processes etc. ..but honestly I haven’t really understood the details of these delays.
The sum total of these individual lists are the new cases reported on the RKI dashboard under the heading COVID-19 Fälle.
However, these cases are then assign to the RKI-DB according to the confirmation date and the CSV is a download from this DB. The cumulated cases/deaths labelled “Gesamt” on the RKI dashboard are also from this database.
This is confusing because one naively assumes diff(Gesamt)=COVID19-Fälle. This is not so!
Diff(Gesamt) is much smoother and less alarming compared to COVID19-Fälle (the most recent value in diff(Gesamt) is always very low compared to COVID19-Fälle) and that make a difference when doing ODE modeling (SEIR and friends). I take the DB data to be more reliable as the confirmation date is taken into account.

Is the RKI cheating?
> I don’t think so. There are good reasons to report worst case scenarios and I think this intention is underlying the current practice (reporting these figures might also be simply a grown habit in the public health system). As a matter of fact diff(Gesamt) looks much less alarming. 

Regarding other data providers:
> Unfortunately, it is not possible to reconstruct the “COVID19-Fälle” from the CSV data.
So far, I have never seen any deviations between the confirmed cases from the CSV (via covid19() in R ) and the RKI dashboard, so everything looks fine from the R side. No need to switch to JHU.

And again:

> Everything said about the “new cases” also applies to the “new deaths”, the death figures are biased to the worse and sometimes much so.
JHU and RKI report different data and it is not really clear where JHU gets the data from. So, I strongly recommend fetching the data from the national health office, i.e. RKI.

I'm going to close this isse. Hope this helps!

**Closed as completed by eguidotti** 2020-12-21 16:51 UTC
