### ISSUE TITLE
Suggestions for additional datasets

### ISSUE THREAD

**Issue by kirienko** [covid19datahub/COVID19#135] opened 2020-11-20 18:35 UTC
It seems that data for Russia, `level=2` is coming from [this repo](https://github.com/grwlf/COVID-19_plus_Russia) which itself is not updating. Of course it's easy to say «That's not our issue but theirs.» But no.

**Comment by eguidotti** [comment] 2020-11-20 18:37
Have you tried to contact them? Can you suggest other data sources we can use instead? Thanks

**Comment by kirienko** [comment] 2020-11-20 20:00
No, I didn't try. There is an [open issue](https://github.com/grwlf/COVID-19_plus_Russia/issues/7) there. And although the repo was updated since that issue was opened, it doesn't seem to be done on regular basis (i.e. in automated fashion).

I would suggest to use [this source](https://github.com/alexei-kouprianov/COVID.2019.ru) which looks more automated. But since I'm by no means affiliated with those people, I cannot guarantee it works better.

**Comment by kirienko** [comment] 2020-11-23 12:37
Well, it turned out that the [main JHU repo](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports) has actual `level=2` data for Russia. I think it's the best choice.

**Comment by eguidotti** [comment] 2020-11-25 01:13
Thanks for the suggestion. But unfortunately I'm not able to find the historical data for the regions in the JHU repo (see [here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)). 
I'm cross checking the data with the [source](https://github.com/alexei-kouprianov/COVID.2019.ru) you suggested so to move to this new one

**Comment by eguidotti** [comment] 2020-11-30 17:48
Hi @kirienko. After speding some time I was not able to validate the data from the other repo. Moreover, I'm afraid it may be discountinued as well in the future. I agree that the best choice would be JHU since it seems there are not open governmental data for Russia (this is what they said when we tried to contact them some months ago). 
I opened [an issue](https://github.com/CSSEGISandData/COVID-19/issues/3403) at JHU repo to ask if they are going to add the Russian regions in the time series dataset. That would be great and easy to integrate. Otherwise, we'd need to do that by hand, but would require a lot of work.

**Comment by kirienko** [comment] 2020-12-01 11:06
Hi @eguidotti. Thank you so much for your efforts! I really appreciate your work!

**Comment by greg-minshall** [comment] 2021-04-18 13:38
hi.  i have been pulling and cleaning up the JHU data, more or less since the beginning.  just having been pointed in your direction, i was thinking of converting to your data.  but, it's true that the [data](somenumbers.info/covid-19/csvs/wide-entire.csv.gz) i've been processing might have some data you want.  if you want daily changes, you'd want the columns whose names end in "_Changes_1".

my github repository is [here](https://gitlab.com/minshall/covid-19), though i wouldn't want to be the first person other than me trying to actually do a build.

if you're interested, and have any questions, please let me know.  cheers!

**Comment by eguidotti** [comment] 2021-04-18 13:51
Hi @greg-minshall and thanks for your message.
Do you have region-wise data for Russia? That would be quite interesting. Also, are you hosting the data you generate somewhere? I couldn't find them. Thanks!

**Comment by greg-minshall** [comment] 2021-04-18 14:11
hosting is [here](https://somenumbers.info/covid-19/world.html).  yes, there is oblast, etc., for Russia, for example, [here](https://somenumbers.info/covid-19/province-rus-per-1e5-capita.html?wexs=Confirmed_Per_1e5_Capita) -- assuming that's sort of what you are hoping for.

**Comment by greg-minshall** [comment] 2021-04-18 14:14
btw: the README.org in my repo had old links; i've just changed that (in case you poke around), hopefully correctly.  cheers.

**Comment by eguidotti** [comment] 2021-04-18 16:53
@greg-minshall Well actually, it looks quite interesting! It seems to me the file I could easily integrate in this repository is the following: https://somenumbers.info/covid-19/csvs/coleaned.csv.gz 

Just a couple of questions:
- is the file updated daily?
- is there a link to the cleaning performed on the JHU data?
- do you have a title/citation for your project? I'd need to put this in the data sources if we decide to integrate it.

Thanks!

**Comment by greg-minshall** [comment] 2021-04-18 17:25
@eguidotti coleaned is basically a cleaned up version of the the entire run of JHU "daily" files.

yes, the files are updated daily.  i think, in the past six months, there have been only a few glitches, maybe one time when something changed in the JHU data.

i don't have a citation.  you can just say "Greg Minshall", some such.  or, a pointer to the repo.

if coleaned works, that's great, as it's the smallest file, and you'll be the closest to JHU (in terms of me messing with the data).

the cleaning performed?  you can look in `covid19.org` in the repo (not that you'd want to), in a section `colean.R`.  part (`compute_intervals`) is dealing with early times when, e.g., Australia (i think) was represented for a while by Australia, then by some of the regions, then back to the country, etc.

then (`propagating`, but also in `colean`) deals with making sure that every entity has an entry for every date after it first appears.  it is very slow, doing lots of `dplyr::group_by()`, etc.  (at some point i'd like to switch to data.table, partly in the hopes it might be faster; and, actually, it's my memory of the complexity of the cleaning code that gives me pause.)

i also drop some JHU columns
````
known_excludes <- c("Incidence_Rate", "Case-Fatality_Ratio", "Incident_Rate", "Case_Fatality_Ratio")
````
as i think i can derive those from the existing data.  (though, in fact, i don't.)

there's filtering: remove duplicates, take only the last observation (`Last_Update`) from a given date.

i add FIPS and Iso3c columns.

there's also some textual transformations (`dosed` and friends -- see the file `fixups.sed` in the repo) on the .csv files, to deal with anomalies early on.

that seems to be about it.

**Comment by greg-minshall** [comment] 2021-04-19 01:58
i realized in my listing of transformations i missed some bits that used to be in the file `fixups.sed`, but are now embedded in `covid19.org`, in a table `csvsedtable` inside the `csvsed` header.  these mostly normalize names at the `Country_Region`, `Province_State`, and `Admin2` levels; plus some fiddling with the odd `FIPS`.

**Comment by eguidotti** [comment] 2021-04-19 14:37
Thanks @greg-minshall for the information. I have integrated the data for Russia. Let's wait a couple of hours for the workflow to complete and see if we can close this long-standing issue.

I was also interested in the `recovered` cases for USA. But I see only very few observations (dates) for each state. E.g. Alabama has only about 10 observations in https://somenumbers.info/covid-19/csvs/coleaned.csv.gz Is it the same in JHU data?

As far as I understand, the other files are aggregating the numbers. E.g. compute the totals for Alabama by summing up together all entries that include Alabama as the upper level in the combined key. Is that correct? At a first stage of this project, I was also aggregating the data in this way but then I noticed that it usually doesn't work. In my experience, they almost never matched with the data provided directly for the upper level. For instance, if only one city is missing in the data, the aggregated state-wise counts are downward biased. Moreover, the data released for the upper level may include travelers or cases in which it is not known the exact location. So unfortunately I won't be able to use the aggregated data.

**Comment by greg-minshall** [comment] 2021-04-19 16:33
@eguidotti, you're welcome.  i hope it helps.  let me know.

i only use JHU data.

i think 'Recovered' comes from JHU's `csse_covid_19_data/csse_covid_19_daily_reports_us` series.  i have a (very recent) "issue" in my repo to remove that series.  i think they started recording that, then discontinued (probably the data wasn't reliable).

yes, you're right about the aggregation technique.  i think when i originally did that work i did some verification.  if i look at the JHU data now, for example, for California on 2021-04-04 (`csse_covid_19_data/csse_covid_19_daily_reports/04-04-2021.csv`), i don't seem to see numbers at the state level, only at the Admin2 (county) level.  for Canada, i only see data for the provinces/territories, not for the country as a whole.  so, in my experience, there is no "data provided directly for the upper level" (a situation which makes me happy, being a believer in second normal form :).

were you looking at these "daily reports"?  or, the more often used "time series" (that's a set of data i don't use so am not familiar with).

**Comment by eguidotti** [comment] 2021-04-20 08:22
@greg-minshall yes, it works and I'm going to close this issue. Thanks a lot!

> were you looking at these "daily reports"? or, the more often used "time series"

Time series data 

> there is no "data provided directly for the upper level" 

I guess that's the case for JHU. What I mean with "the data released for the upper level" are actually data that are released directly from the government for the upper level (not necessarily US, but around the world). In general, when I aggregated data from the lower levels I never got the counts provided for the upper level. Also, in many cases JHU data (aggregated or not) do not match the ones available from open governmental data. That's basically the motivation behind this repo :) We try to pull the data from the official providers whenever possible. But in many cases it is not possible, and works like yours are very useful!

**Comment by greg-minshall** [comment] 2021-04-20 11:44
@eguidotti ah, "ground truth", or whatever the saying is.  no, i decided early on that for me, `JHU == Truth`.

btw, i've killed off the embarrassing `Recovered`, et al.

also, if you ever wanted (as a backup, say, to my build process), probably producing  a daily `coleaned.csv` file would be reasonably easy for you to do in-house (using the R script i provide).

**Comment by eguidotti** [comment] 2021-04-20 13:18
Ok I downloaded your repo as a backup, but I hope everything will go smoothly. Thanks again!

**Comment by greg-minshall** [comment] 2021-09-09 06:59
is it legal, useful, to post to a closed issue?

anyway, @eguidotti, you might look at [this issue](https://gitlab.com/minshall/covid-19/-/issues/68) on my site.

i won't do anything about this soon, but that data set might also appeal to you (instead of my coleaned.csv).  i'll be curious of your thoughts.

cheers.

**Comment by eguidotti** [comment] 2021-09-09 13:25
Hi @greg-minshall, thanks for posting this!
It looks quite interesting to me. Not only for the data itself, but also to standardize the [Geospatial ID](https://github.com/CSSEGISandData/COVID-19_Unified-Dataset#geospatial-id). I guess this would make much easier for users to match the data by administrative area with external providers.
I'll reopen this as a reminder for me to get it done, or maybe some volunteer shows up :)
Many thanks!

**Comment by greg-minshall** [comment] 2021-09-09 14:58
> It looks quite interesting to me. Not only for the data itself, but also to standardize the [Geospatial ID](https://github.com/CSSEGISandData/COVID-19_Unified-Dataset#geospatial-id). I guess this would make much easier for users to match the data by administrative area with external providers.

yes, i agree.  cheers!

**Comment by eguidotti** [comment] 2021-11-09 16:46
After months of work... it's done! The new version is available. Please [see the changelog](https://covid19datahub.io/news/index.html)

**Closed as completed by eguidotti** 2021-11-09 16:46 UTC

**Comment by greg-minshall** [comment] 2021-11-10 15:44
Emanuele, congratulations.  are you still pulling from my data (for states/provinces/oblasts)?  just so i can feel un-guilty if/when my builds break... :)

**Comment by eguidotti** [comment] 2021-11-10 17:29
Hi Greg, I have switched to the JHU unified dataset as you suggested. Many thanks for your package and your input, it has been very useful!

**Comment by greg-minshall** [comment] 2021-11-10 17:42
good -- enjoy!
