### ISSUE TITLE
Wrong export of German Covid Data to csv

### ISSUE THREAD

**Issue by guenterhack** [covid19datahub/COVID19#131] opened 2020-11-01 14:02 UTC
Hi!
There seems to be an issue with the Covid data csv for Germany. If I fetch the data via R, I get 499.694 confirmed cases for the 2020-10-30, which is correct. In the csv, it's 44.924. All the case data is way too low in the csv. Perhaps it has been mixed up with another country?

**Comment by vzemlys** [comment] 2020-11-01 14:22
The same as #130

**Comment by eguidotti** [comment] 2020-11-01 16:51
Hi @guenterhack, thanks for your message. 
The data for Germany are not mixed up with any other country. The problem is that the RKI-URL seems not to be very well maintained. So it is randomly returning only a fraction of data every now and then. I updated to the new recommended URL. This should be fixed in #130

**Comment by guenterhack** [comment] 2020-11-01 17:01
Great work, @eguidotti ! Thank you again!

**Closed as completed** 2020-11-01 18:43 UTC
