### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#98] opened 2020-08-11 02:13 UTC
Update at level 2 not there even though source data are current. This is turning out to be a recurrent and frustrating issue. Sorry, but I just needed to say it because we are very reliant on your data - we have built our platform of surveillance on it.

**Comment by eguidotti** [comment] 2020-08-11 10:29
Hello @kenshermock, I understand and I'm sorry to hear that.
This should be fixed and the new data will go live in a couple of hours. 

We received the alert about it thanks to the latest automatic tests. These issues are due to the data providers updating the data format and require manual intervention (Sweden in this case). They are usually fixed in 24h but I understand it can be annoying missing updates every now and then.

I'll try to restructure the fallback mechanism when some data sources are failing so to make sure the other sources are not affected while waiting for the manual fix. 
In any case please note that we are all volunteers and the hub is [not meant for commercial purposes](https://covid19datahub.io/LICENSE.html).

Hope this helps.
Best,
-- Emanuele

**Comment by eguidotti** [comment] 2020-08-12 13:14
Hello @kenshermock, 
the new fallback mechanism and tests are now live. 

The updates will not be frozen any longer. When a data source fails, it will be temporarily removed from the hub while waiting for the manual fix. The other sources will continue to work.

On the other hand, this means that you may see some data disappear if the corresponding sources change e.g. the data format. We usually try to fix this in 24h, but I'm afraid these changes are out of our control. Best

**Closed as completed by eguidotti** 2020-08-12 13:14 UTC

**Comment by malouche** [comment] 2020-08-17 09:14
The data about France is very different from the official published data.

**Comment by eguidotti** [comment] 2020-08-17 17:34
Hi @malouche, thank you for your message! Would you mind opening a different issue on this?

I'm trying to figure out which differences you noticed. Are you talking about national level data for France? Or maybe regional level? Also, can you please provide the link to the official published data you are comparing with? That would help a lot to look deeper into this.

Many thanks!

**Comment by malouche** [comment] 2020-08-18 07:47
When I had update the data yesterday 8/17 at 8am (GMT+1) the cases on 8/16 was ~ 23,000. When I had updated  later at 1pm (GMT+1), it was ~3000 (it’s the correct number). However, there are two outliers in France data (at the national level):
- July 15, ~25K cases
- August 13, ~24K
And France is of the countries where we still can find negative daily cases (and deaths too).

Question: When is the best time to update the data?
Thank you


On Aug 17, 2020, at 6:35 PM, Emanuele Guidotti <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @malouche<https://github.com/malouche>, thank you for your message! Would you mind opening a different issue on this?

I'm trying to figure out which differences you noticed. Are you talking about national level data for France? Or maybe regional level? Also, can you please provide the link to the official published data you are comparing with? That would help a lot to look deeper into this.

Many thanks!

**Comment by eguidotti** [comment] 2020-08-18 09:17
Hi @malouche, the data for France are pulled from https://github.com/opencovid19-fr/data You may look there to understand the best time to update the data.

Regarding the numbers you are writing, I find them very strange. I see 219,029 cases on 8/16, which is quite different from both  ~23,000 or ~3,000. And for the other dates I see:

- July 15, 173K cases
- August 13, 209K cases

All these counts are in line with other online data providers.

> And France is of the countries where we still can find negative daily cases (and deaths too).

I see no negative counts in national level data for France in the hub.
Am I missing something? Can you post the code you are using?

Cheers

**Comment by malouche** [comment] 2020-08-18 10:35
Thank you for your replay. I really appreciate it. I use R and here’s below my code to get the France data from the link that you had provided to me


dcov_fr<-read.csv("https://raw.githubusercontent.com/opencovid19-fr/data/master/dist/chiffres-cles.csv")

dcov_fr1=dcov_fr%>%filter(granularite=="pays" & source_type=="ministere-sante")

dcov_fr1=dcov_fr1%>%mutate(new_cases=c(cas_confirmes[1],diff(cas_confirmes)))%>%select(date,cas_confirmes,new_cases)

dcov_fr2=dcov_fr%>%filter(granularite=="pays" & source_type=="sante-publique-france")

dcov_fr2=dcov_fr2%>%mutate(new_cases=c(cas_confirmes[1],diff(cas_confirmes)))%>%select(date,cas_confirmes,new_cases)


dcov_frA=dcov_fr1%>%full_join(dcov_fr2,by="date")

You can check that the data from "ministere-sante” is complete  and looks better than the one from "sante-publique-france. It has two negative new_cases.

However, here’s my R code when I use COVID19 package and extract the France data. It’s somewhat different from the data above and the new_cases has one extreme valus close to 25K  and three negative new_cases

dcov1=COVID19::covid19(cache = F)
dcov1=dcov1%>%filter(confirmed>0)%>%group_by(id)%>%arrange(date, .by_group = TRUE)%>%
  filter(administrative_area_level==1)%>%
  select(date,administrative_area_level_1,confirmed,deaths,recovered,population)%>%
  rename(country=administrative_area_level_1,iso3c=id)

dcov1=dcov1%>%select(date,iso3c,confirmed,recovered,deaths)

dcov_frB=dcov1%>%filter(iso3c=="FRA")%>%mutate(new_cases=c(confirmed[1],diff(confirmed)))


Thank you again for the great job!



On Aug 18, 2020, at 10:17 AM, Emanuele Guidotti <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @malouche<https://github.com/malouche>, the data for France are pulled from https://github.com/opencovid19-fr/data You may look there to understand the best time to update the data.

Regarding the numbers you are writing, I find them very strange. I see 219,029 cases on 8/16, which is quite different from both ~23,000 or ~3,000. And for the other dates I see:

  *   July 15, 173K cases
  *   August 13, 209K cases

All these counts are in line with other online data providers.

And France is of the countries where we still can find negative daily cases (and deaths too).

I see no negative counts in national level data for France in the hub.
Am I missing something? Can you post the code you are using?

Cheers

**Comment by eguidotti** [comment] 2020-08-18 14:11
Hi @malouche, thank you for the info.
Yes we are using the `"ministere-sante”` source. 

> It’s somewhat different from the data above and the new_cases has one extreme valus close to 25K  and three negative new_cases

This was due to missing data from `"ministere-sante` that were filled with [JHU data](https://github.com/CSSEGISandData/COVID-19). I removed this fallback mechanism. The data should be fixed now. Please try again in a couple of hours and let me know if that worked for you.
```R
# make sure to have the CRAN version installed
install.packages("COVID19")
# load the package
require("COVID19")
# download data for France, level 1 (national level)
x <- covid19("FRA", level = 1)
# compute daily counts
x$confirmed_new <- c(NA, diff(x$confirmed))
```
Thanks!
