### ISSUE TITLE
France data is not updating

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#157] opened 2021-03-03 00:29 UTC
For France, covid-related data (cases, deaths, etc) have not updated since 2/19.

**Comment by eguidotti** [comment] 2021-03-03 10:00
Hi @hlcny, thanks for spotting this! I notified the data provider here: https://github.com/opencovid19-fr/data/issues/570

**Comment by PowershellNinja** [comment] 2021-03-19 15:20
Until this is resolved, we are using a workaround to at least get the cases data (there are more columns, cases is the only that really matters to us right now) directly from the French government website.

Our solution looks like this, in case anyone needs that data too:
```Python
from covid19dh import covid19
import requests
import pandas as pd

pdf, src = covid19(verbose=False)

column_renames = {
    "maille_code": "id",
    "conf": "confirmed",
}

#Download French Government Data to File
govFR_file = "data-gouv-fr-chiffres-cles.csv"
govFR_url = (
    "https://www.data.gouv.fr/fr/datasets/r/f335f9ea-86e3-4ffa-9684-93c009d5e617"
)

#Download File
file = requests.get(govFR_url)
with open(govFR_file, "wb") as f:
    f.write(file.content)
#Load csv into pandas
data_govFR = pd.read_csv(govFR_file)

#Rename Columns
data_govFR.rename(column_renames, axis="columns", inplace=True)

#Get Date for last valid reported case data on covid19dh
lastReportedValidDate = datetime.strptime("19-02-2021", "%d-%m-%Y")

#Convert date column to date
data_govFR["date"] = pd.to_datetime(data_govFR["date"])
#Get only rows where date is greated than the last date where valid data was available in covid19dh
data_govFR = data_govFR.loc[data_govFR["date"] > lastReportedValidDate]
#Filter out rows where confirmed is N/A
data_govFR = data_govFR.loc[~data_govFR["confirmed"].isna()]

#Copy values from French government dataset to covid19dh dataset
for currentDate in data_govFR["date"].dt.date.unique().tolist():
  pdf.loc[(pdf["id"]=="FRA") & (pdf["date"].dt.date == currentDate), "confirmed"] = data_govFR.loc[data_govFR["date"].dt.date == currentDate, "confirmed"].values
```
You can then check that there are confirmed cases for France in your data again by using:
```Python
pdf.loc[(pdf["id"]=="FRA") & (pdf["date"] > lastReportedValidDate)]
```

**Comment by eguidotti** [comment] 2021-03-22 22:37
Thanks @PowershellNinja for the hint!
I should have fixed this in the latest commit (not only confirmed cases, but the whole data available).
The data should be back in a couple of hours. I checked them manually and the data seem to be consistent with the previous ones pulled from https://github.com/opencovid19-fr/data But please let me know if you find any inconsistencies. Otherwise I'm going to close the issue. Thanks!

**Comment by eguidotti** [comment] 2021-03-25 10:47
Seems fixed.

**Closed as completed by eguidotti** 2021-03-25 10:47 UTC

**Comment by PowershellNinja** [comment] 2021-03-29 07:34
I can confirm it is fixed, thanks for your time @eguidotti :)
